<definition> ::= <mut>? <identifier> : <type> = <statement>;

<assignation> ::= = <statement>;
<scope> ::= { <statement>;+ }


<type> ::= <>
<basetype> ::= void | bool | char | byte | u8 | i8 | f8 | u16 | i16 | f16 | glyph | u32 | i32 | f32 | u64 | i64 | f64 | size | usize | type;
<function> ::= <identifier>()
